name: CD
on:
  push:
    tags:
      - v*
jobs:
  Publish_at_npm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        registry-url: https://registry.npmjs.org/

    - name: Publish
      run: npm run publish:cd
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
